version: "3.7"

services:
  server:
    container_name: api-server
    image: api-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  mongo-db:
    container_name: mongo-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo-db
    ports:
      - 8081:8081
    networks:
      - mongo-network
    restart: unless-stopped

networks:
  mongo-network:
    driver: bridge
